#ifndef __MANTICORE_AXI_REGISTERS_H__
#define __MANTICORE_AXI_REGISTERS_H__
namespace manticore {
namespace registers {

// These are generated by the hardware chisel code.
struct Control {
  static constexpr int base = 0;
  static constexpr int width = 32;
};
struct ExceptionId {
  static constexpr int base = 16;
  static constexpr int width = 32;
};
struct TraceDumpHead {
  static constexpr int base = 24;
  static constexpr int width = 64;
};
struct DeviceInfo {
  static constexpr int base = 36;
  static constexpr int width = 32;
};
struct CycleCount {
  static constexpr int base = 44;
  static constexpr int width = 64;
};
struct VirtualCycleCount {
  static constexpr int base = 56;
  static constexpr int width = 64;
};
struct BootloaderCycleCount {
  static constexpr int base = 68;
  static constexpr int width = 32;
};
struct ClockStalls {
  static constexpr int base = 76;
  static constexpr int width = 64;
};
struct CacheHits {
  static constexpr int base = 88;
  static constexpr int width = 64;
};
struct CacheMisses {
  static constexpr int base = 100;
  static constexpr int width = 64;
};
struct CacheStalls {
  static constexpr int base = 112;
  static constexpr int width = 64;
};
struct ScheduleConfig {
  static constexpr int base = 124;
  static constexpr int width = 64;
};
struct TraceDumpBase {
  static constexpr int base = 136;
  static constexpr int width = 64;
};
struct GlobalMemoryInstructionBase {
  static constexpr int base = 148;
  static constexpr int width = 64;
};
struct DramBank0Base {
  static constexpr int base = 160;
  static constexpr int width = 64;
};
}; // namespace registers
}; // namespace manticore

#endif